version: '3'

services:
  front-end-system-dev:
    container_name: fe-dev
    build:
      context: .
      dockerfile: front-end-dev.dockerfile
    ports:
      - '3030:3030'
  front-end-system-prd:
    container_name: fe-prd
    build:
      context: .
      dockerfile: front-end-prd.dockerfile
    ports:
      - '3333:3333'
